name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'
      - run: nuget restore FlashCom.sln
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: msbuild FlashCom.sln /p:ProjectName="FlashCom" /p:Configuration="Release" /p:Platform="x64" /p:AppxBundle="Always" /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="feedcf964fdcb3e04e4b27f86536cb269e40f873" /p:PackageCertificateKeyFile="Packaging_TemporaryKey.pfx" /p:UapAppxPackageBuildMode="Sideload" /p:AppxBundlePlatforms="x64|ARM64" /p:AppxPackageDir="AppPackages"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppPackage
          path: src/Packaging/AppPackages
